apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: storagedevicesets.ocs.openshift.io
spec:
  group: ocs.openshift.io
  names:
    kind: StorageDeviceSet
    listKind: StorageDeviceSetList
    plural: storagedevicesets
    singular: storagedeviceset
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
